### ISSUE TITLE
Error when trying to retrieve app reviews

### ISSUE THREAD

**Issue by jobreu** [JsLth/steamr#1]
Thx for creating this neat package! When I tried to retrieve reviews following the example from the documentation website, I get the following error:

`Fehler in get_app_reviews(appid, day_range = day_range, start_date = start_date,  : 
  Objekt 'summary_num_positive_reviews' nicht gefunden`

Code:

`
library(steamr)
apps <- search_apps("team fortress")
appid <- apps$appid

reviews <- get_all_app_reviews(appid[1])
`

*Note*: I get the same error when using `get_app_reviews()` instead of `get_all_app_reviews()`

**Comment by JsLth** [comment]
Whoops, looks like I broke the code when I made some adjustments yesterday! It should work now but I should fully sanitize the code base at some point.

**Comment by jobreu** [comment]
Can confirm that it works now! Thx a lot for the quick fix :-)
